# Generated by Django 4.2.16 on 2024-10-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('name', models.CharField(choices=[('AB', 'AB'), ('CD', 'CD'), ('EF', 'EF'), ('GH', 'GH')], max_length=100, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration', models.CharField(max_length=20)),
                ('room', models.CharField(choices=[('Møderum 1', 'Møderum 1'), ('Møderum 2', 'Møderum 2')], max_length=20)),
            ],
        ),
    ]
